# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  name = "FAQ"
  url = "/faq/"
  weight = 2

[[main]]
  name = "Schedule of Topics"
  url = "/syllabus/"
  weight = 3

[[main]]
  name = "Homework"
  url = "/homework/"
  weight = 4

[[main]]
  name = "Setup"
  url = "/setup/"
  weight = 5

[[main]]
  name = "Notes"
  url = "/notes/"
  weight = 6

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
